cbail:
  - "*"
lukebaker:
  - "*"
msalganik:
  - "*"
matnel:
  - "_data/2018/helsinki/"
  - "2018/helsinki/"
  - "2018/live-stream.md"
juhopaak:
  - "_data/2018/helsinki/"
  - "2018/helsinki/"
  - "2018/live-stream.md"
UMTti:
  - "_data/2018/helsinki/"
  - "2018/helsinki/"
  - "2018/live-stream.md"
joshua-a-becker:
  - "_data/2018/chicago/"
  - "2018/chicago/"
  - "2018/live-stream.md"
dgzara:
  - "_data/2018/chicago/"
  - "2018/chicago/"
  - "2018/live-stream.md"
allisonmorgan:
  - "_data/2018/boulder/"
  - "2018/boulder/"
  - "2018/live-stream.md"
visseho:
  - "_data/2018/capetown/"
  - "2018/capetown/"
  - "2018/live-stream.md"
ccgilroy:
  - "_data/2018/seattle/"
  - "2018/seattle/"
  - "2018/live-stream.md"
MariaYR:
  - "_data/2018/hunter-nyc/"
  - "2018/hunter-nyc/"
  - "2018/live-stream.md"
ausmani23:
  - "_data/2018/nyu-nyc/"
  - "2018/nyu-nyc/"
  - "2018/live-stream.md"
fmerhout:
  - "_data/2018/"
  - "assets/images"
  - "2018/"
marcone84:
  - "_data/2018/"
  - "2018/"
  - "assets/images"
taylorwhitten:
  - "_data/2018/"
  - "2018/"
  - "assets/images"
