cbail:
  - "*"
lukebaker:
  - "*"
msalganik:
  - "*"
matnel:
  - "_data/2018/helsinki/"
  - "2018/helsinki/"
joshua-a-becker:
  - "_data/2018/northwestern/"
  - "2018/northwestern/"
  - "_data/2018/chicago/"
  - "2018/chicago/"
allisonmorgan:
  - "_data/2018/boulder/"
  - "2018/boulder/"
visseho:
  - "_data/2018/capetown/"
  - "2018/capetown/"
